// Tests the distribution generated by Java's Math.random() function.
public class TestRandom {
	public static void main(String[] args) {
		int range = Integer.parseInt(args[0]);
		int greaterHalfCnt = 0;
		int lessHalfCnt = 0;

		for (int i = 0; i < range; i++) {
			double rnd = Math.random();
			if (rnd > 0.5) {
				greaterHalfCnt++;
			} else {
				lessHalfCnt++;
			}
		}

		System.out.println("> 0.5: " + greaterHalfCnt + " times");
		System.out.println("<= 0.5: " + lessHalfCnt + " times");

		if (lessHalfCnt != 0) {
			System.out.println("Ratio: " + (double) greaterHalfCnt / lessHalfCnt);
		}
	}
}
